---
baseURL: https://sszgr.com/
languageCode: zh-CN
theme: LeaveIt
title: 洛丶
paginate: 12
enableEmoji: true
hasCJKLanguage: true
preserveTaxonomyNames: true
menu:
  main:
    - name: 文章
      url: /posts/
      weight: 1
    - name: 分类
      url: /categories/
      weight: 2
    - name: 标签
      url: /tags/
      weight: 3
    - name: 关于我
      url: /about/
      weight: 4
params:
  author: 洛丶
  avatar: /images/avatar.jpg
  beian: "京ICP备2021040670号"
  hidecredits: true
  license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'
  since: 2019
  subtitle: 无用之用，方为大用
  social:
    GitHub: sszgr
permalinks:
  posts: /:year/:filename/
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: solarized-light
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
